import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import SectionTitle from "../components/SectionTitle";
import { useAuth } from "../context/AuthContext";
import api from "../utils/api";

const Community = () => {
  const [loading, setLoading] = useState(true);
  const [posts, setPosts] = useState([]);
  const [activeMenu, setActiveMenu] = useState(null);

  const navigate = useNavigate();
  const { isLoggedIn, setIsAuthModalOpen } = useAuth();

  const fetchPublicProjects = async () => {
    try {
      const response = await api.get("/projects/public");
      setPosts(response.data.projects || []);
      setLoading(false);
    } catch (err) {
      console.error(err);
      setLoading(false);
    }
  };

  useEffect(() => {
    if (isLoggedIn) {
      fetchPublicProjects();
    } else {
      setLoading(false);
    }
  }, [isLoggedIn]);

  useEffect(() => {
    const closeMenu = () => setActiveMenu(null);
    window.addEventListener("click", closeMenu);
    return () => window.removeEventListener("click", closeMenu);
  }, []);

  const handleDownloadImage = async (url, name) => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const blobURL = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobURL;
      link.download = `${name.replace(/\s+/g, "_")}_image.jpg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(blobURL);
    } catch (e) {
      window.open(url, "_blank");
    }
  };

  const handleDownloadVideo = async (url, name) => {
    if (!url) return alert("No video generated for this project yet.");
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const blobURL = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = blobURL;
      link.download = `${name.replace(/\s+/g, "_")}_video.mp4`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(blobURL);
    } catch (e) {
      window.open(url, "_blank");
    }
  };

  const handleShare = (post) => {
    const shareUrl = `${window.location.origin}/result/${post.id}`;
    navigator.clipboard.writeText(shareUrl);
    alert("Project result link copied to clipboard!");
  };

  // AUTH REQUIRED STATE
  if (!isLoggedIn) {
    return (
      <div className="min-h-[80vh] flex flex-col items-center justify-center p-6 bg-[#f9fafb] mt-12">
        <div className="max-w-md w-full bg-white p-8 rounded-2xl shadow-xl text-center border border-slate-100">
          <div className="w-16 h-16 bg-indigo-50 text-indigo-600 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl">
            🌎
          </div>
          <h2 className="text-2xl font-bold text-gray-800 mb-2">Explore Community</h2>
          <p className="text-gray-500 mb-8">
            Please sign in or create an account to browse public video showcases generated by the AdVid community.
          </p>
          <button
            onClick={() => setIsAuthModalOpen(true)}
            className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-3 px-6 rounded-xl transition cursor-pointer shadow-lg hover:shadow-indigo-200"
          >
            Sign In / Register
          </button>
        </div>
      </div>
    );
  }

  // LOADER
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#f9fafb]">
        <div className="flex flex-col items-center gap-3">
          <div className="w-10 h-10 border-4 border-indigo-600 border-t-transparent rounded-full animate-spin"></div>
          <p className="text-gray-500 font-medium text-sm">Loading community feed...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#f9fafb] px-6 md:px-16 py-20 mt-12">
      <div className="max-w-6xl mx-auto">
        {/* Heading */}
        <div className="mb-16 text-center">
          <SectionTitle
            text2="Community"
            text3="See what others are creating with AdVid"
          />
        </div>

        {posts.length === 0 ? (
          <div className="max-w-3xl mx-auto bg-white border border-slate-100 rounded-2xl p-10 text-center shadow-sm">
            <h2 className="text-xl font-semibold text-gray-800 mb-2">
              No public creations yet
            </h2>
            <p className="text-gray-500 mb-6">
              Be the first to publish a stunning AI video showcase!
            </p>
            <button
              onClick={() => navigate("/generate")}
              className="bg-indigo-600 hover:bg-indigo-750 text-white px-6 py-3 rounded-lg transition font-medium cursor-pointer"
            >
              Create New Generation
            </button>
          </div>
        ) : (
          /* GRID */
          <div className="columns-1 sm:columns-2 md:columns-3 gap-6 space-y-6">
            {posts.map((post) => (
              <div
                key={post.id}
                className="break-inside-avoid rounded-xl bg-white shadow-sm relative border border-slate-100 hover:shadow-md transition overflow-hidden"
              >
                {/* IMAGE */}
                <div className="relative group overflow-hidden">
                  <img
                    src={post.combined_image_url}
                    alt={post.name}
                    className="w-full h-auto object-cover transition duration-500 group-hover:scale-[1.02]"
                  />

                  {/* VIDEO */}
                  {post.video_url && (
                    <video
                      src={post.video_url}
                      muted
                      loop
                      className="absolute top-0 left-0 w-full h-full object-cover opacity-0 group-hover:opacity-100 transition duration-300"
                      onMouseEnter={(e) => e.target.play()}
                      onMouseLeave={(e) => e.target.pause()}
                    />
                  )}

                  {/* ASPECT */}
                  <div className="absolute top-3 left-3 bg-black/60 text-white text-[10px] px-2 py-0.5 rounded">
                    {post.aspect_ratio || "9:16"}
                  </div>

                  {/* 3 DOT MENU */}
                  <div className="absolute top-3 right-3 z-10">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setActiveMenu(activeMenu === post.id ? null : post.id);
                      }}
                      className="bg-black/60 hover:bg-black/80 text-white px-2 py-0.5 rounded-md cursor-pointer font-bold"
                    >
                      ⋮
                    </button>

                    {activeMenu === post.id && (
                      <div
                        onClick={(e) => e.stopPropagation()}
                        className="absolute right-0 mt-2 w-44 bg-[#2f2f2f]/90 backdrop-blur-md text-white rounded-xl shadow-lg p-2 space-y-1 z-50 text-xs"
                      >
                        <button
                          onClick={() => handleDownloadImage(post.combined_image_url, post.name)}
                          className="block w-full text-left px-3 py-2 hover:bg-gray-700 rounded cursor-pointer"
                        >
                          Download Image
                        </button>

                        <button
                          onClick={() => handleDownloadVideo(post.video_url, post.name)}
                          className="block w-full text-left px-3 py-2 hover:bg-gray-700 rounded cursor-pointer"
                        >
                          Download Video
                        </button>

                        <button
                          onClick={() => handleShare(post)}
                          className="block w-full text-left px-3 py-2 hover:bg-gray-700 rounded cursor-pointer"
                        >
                          Share Link
                        </button>
                      </div>
                    )}
                  </div>
                </div>

                {/* CONTENT */}
                <div className="p-4 space-y-2">
                  <p className="font-semibold text-gray-800">{post.name}</p>

                  <p className="text-[10px] text-gray-400">
                    Created: {new Date(post.created_at).toLocaleDateString()}
                  </p>

                  {post.product_description && (
                    <p className="text-sm text-gray-600 line-clamp-2">
                      {post.product_description}
                    </p>
                  )}

                  {post.user_prompt && (
                    <p className="text-xs text-gray-400 italic truncate">
                      "{post.user_prompt}"
                    </p>
                  )}

                  {/*  BUTTONS */}
                  <div className="pt-2">
                    <button
                      onClick={() => navigate(`/result/${post.id}`)}
                      className="w-full border border-slate-200 py-2 rounded-lg text-xs font-semibold hover:bg-slate-50 transition cursor-pointer text-slate-700 text-center"
                    >
                      View Details & Ad Video
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default Community;